# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbot', '0006_auto_20170603_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='state',
            field=models.IntegerField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
