# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbot', '0008_auto_20170603_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='address',
            field=models.CharField(default='home', max_length=100),
            preserve_default=False,
        ),
    ]
