# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbot', '0009_userinfo_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
    ]
